/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const add_Knowledgebase_Logic = require('./code/add-knowledgebase-logic');
const delete_AllKnowledgebase_Logic = require ('./code/delete-knowledgebase-logic');
const delete_KnowledgebaseDocument_Logic = require ('./code/delete-knowledgebase-document-logic');
const chat_Logic = require ('./code/chat-logic');

class GenieService extends LCAPApplicationService {
    async init() {

        this.after('UPDATE', 'KnowledgeBase.attachments.drafts', async (results, request) => {
            await add_Knowledgebase_Logic(results, request);
        });

        this.after('DELETE', 'KnowledgeBase', async (results, request) => {
            await delete_KnowledgebaseDocument_Logic(results, request);
        });

        this.on('deleteEmbeddings', async (request) => {
            return await delete_AllKnowledgebase_Logic(request);
        });

        this.on('chat', async (request) => {
            return await chat_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    GenieService
};